name: habit_tracker
description: A simple habit tracker using SharedPreferences
publish_to: 'none'
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  flutter_staggered_animations: ^1.1.1

flutter: {
  uses-material-design: true
}